spring:
    datasource:
        url: jdbc:mysql://192.168.140.130:3306/freemarker?characterEcoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
        username: root
        password: XMcs@2019
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
   # 搜索指定包别名
   typeAliasesPackage: com.zylpa
   # 配置mapper的扫描，找到所有的mapper.xml映射文件
   mapperLocations: classpath*:mapper/**/*Mapper.xml
   # 加载全局的配置文件
   configLocation: classpath:mapper/mybatis-config.xml
