server:
  port: 8083 #服务端口

spring:
  application:
    name: zylpa-admin #指定服务名
  profiles:
    active: test
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试

