spring:
    datasource:
        url: jdbc:mysql://localhost:3306/freemarker?characterEcoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml     #mapper文件路径
  type-aliases-package: com.zylpa.generator   #实体类的包路径



